# docker-compose.yml

version: '3.8'
services:
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=midas
      - POSTGRES_PASSWORD=midas
      - POSTGRES_DB=ffcs-db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5555:5432'

volumes:
  postgres:
